inputFile = open("piratein.txt","r")
outputFile = open("pirateout.txt","w")
myInput=inputFile.read().split()
l=int(myInput[0])
x=int(myInput[1])
y=int(myInput[2])
ans=min(x+y,2*l-x-y)
outputFile.write(str(ans)+"\n")
inputFile.close()
outputFile.close()
